### ISSUE TITLE
Fixing the Addon Compatibility Issues with Kodi 19 and Python 3

### ISSUE THREAD

**Issue by Mr-7mdan** [robwebset/script.suitability#1]
Hi,

To start, thank you for the effort you invested in developing the addon. It helps a lot of families selecting the proper content.

I fixed a lot of bug, issues, commands, and dependencies to the point I cannot make a changelog.

The addon now is working but I haven't fixed all the scrappers. MovieGuideOrgScraper is the only one working.

I am not a programmer and not familiar with Python enough to fix the scrappers, and to fix adding the button to the VideoDialog.

I hope you could assist in fixing the remaining scrappers, and the VideoDialog. It be might be easy for you

[script.suitability.zip](https://github.com/robwebset/script.suitability/files/9148349/script.suitability.zip)

**Comment by robwebset** [comment]
Hi @Mr-7mdan I'm afraid I haven't worked on Kodi addons for years, so will be unable to help. Can I suggest you check to Kodi forums and see if anyone there is willing to work with you on the addon. Thanks, Rob
